//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplikacjaKontrahentów
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontrahenci
    {
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public string Nip { get; set; }
        public int IdTypu { get; set; }
        public string OpisFirmy { get; set; }
        public bool Aktywny { get; set; }
    }
}
